### ISSUE TITLE
Migration from 1.8.6 -> 1.8.7

### ISSUE THREAD

**Issue by nakata5321** [airalab/homeassistant-robonomics-integration#68]
Provide migration function, which will give the option to update integration from 1.8.6 to 1.8.7 and upper.

## Problem

during tests of 1.8.7-beta, found that I can't update from 1.8.6 to 1.8.7. I get the following error:
```
2024-07-22 15:45:59.846 DEBUG (MainThread) [custom_components.robonomics] Sending interval: 10 minutes
2024-07-22 15:45:59.852 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Robonomics for robonomics
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robonomics/__init__.py", line 186, in async_setup_entry
    hass.data[DOMAIN][ROBONOMICS] = Robonomics(
                                    ^^^^^^^^^^^
  File "/config/custom_components/robonomics/robonomics.py", line 239, in __init__
    self.controller_account: Account = Account(
                                       ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/robonomicsinterface/classes/account.py", line 43, in __init__
    self.keypair: Keypair = create_keypair(seed, crypto_type)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/robonomicsinterface/utils.py", line 28, in create_keypair
    return Keypair.create_from_mnemonic(seed, ss58_format=32, crypto_type=crypto_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/substrateinterface/keypair.py", line 213, in create_from_mnemonic
    keypair = cls.create_from_seed(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/substrateinterface/keypair.py", line 249, in create_from_seed
    raise ValueError('crypto_type "{}" not supported'.format(crypto_type))
ValueError: crypto_type "None" not supported
```
Please, provide in new release migration function to give option to update from 1.8.6 version

**Comment by LoSk-p** [comment]
#69
